In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data_set = pd.read_csv('laptop_data_set.csv')

data= data_set.drop([ 'Price'],axis=1)

data.head()


Unnamed: 0 Company   TypeName  Inches                    ScreenResolution  \
0           0   Apple  Ultrabook    13.3  IPS Panel Retina Display 2560x1600   
1           1   Apple  Ultrabook    13.3                            1440x900   
2           2      HP   Notebook    15.6                   Full HD 1920x1080   
3           3   Apple  Ultrabook    15.4  IPS Panel Retina Display 2880x1800   
4           4   Apple  Ultrabook    13.3  IPS Panel Retina Display 2560x1600   

                          Cpu   Ram               Memory  \
0        Intel Core i5 2.3GHz   8GB            128GB SSD   
1        Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
2  Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
3        Intel Core i7 2.7GHz  16GB            512GB SSD   
4        Intel Core i5 3.1GHz   8GB            256GB SSD   

                            Gpu  OpSys  Weight  
0  Intel Iris Plus Graphics 640  macOS  1.37kg  
1        Intel HD Graphics 6000  macOS  1.34kg  
2         Intel HD Graphics 620  No OS  1.86kg  
3            AMD Radeon Pro 455  macOS  1.83kg  
4  Intel Iris Plus Graphics 650  macOS  1.37kg

In [2]:
for col in data.columns:
    print(col)
    print(data[col].unique())
    print()


Unnamed: 0
[   0    1    2 ... 1300 1301 1302]

Company
['Apple' 'HP' 'Acer' 'Asus' 'Dell' 'Lenovo' 'Chuwi' 'MSI' 'Microsoft'
 'Toshiba' 'Huawei' 'Xiaomi' 'Vero' 'Razer' 'Mediacom' 'Samsung' 'Google'
 'Fujitsu' 'LG']

TypeName
['Ultrabook' 'Notebook' 'Netbook' 'Gaming' '2 in 1 Convertible'
 'Workstation']

Inches
[13.3 15.6 15.4 14.  12.  11.6 17.3 10.1 13.5 12.5 13.  18.4 13.9 12.3
 17.  15.  14.1 11.3]

ScreenResolution
['IPS Panel Retina Display 2560x1600' '1440x900' 'Full HD 1920x1080'
 'IPS Panel Retina Display 2880x1800' '1366x768'
 'IPS Panel Full HD 1920x1080' 'IPS Panel Retina Display 2304x1440'
 'IPS Panel Full HD / Touchscreen 1920x1080'
 'Full HD / Touchscreen 1920x1080' 'Touchscreen / Quad HD+ 3200x1800'
 'IPS Panel Touchscreen 1920x1200' 'Touchscreen 2256x1504'
 'Quad HD+ / Touchscreen 3200x1800' 'IPS Panel 1366x768'
 'IPS Panel 4K Ultra HD / Touchscreen 3840x2160'
 'IPS Panel Full HD 2160x1440' '4K Ultra HD / Touchscreen 3840x2160'
 'Touchscreen 2560x1440' '1600x900' 'IP

In [3]:
data=data.drop(data.iloc[:,0:1],axis=1)

In [4]:
data['Company'].unique()

array(['Apple', 'HP', 'Acer', 'Asus', 'Dell', 'Lenovo', 'Chuwi', 'MSI',
       'Microsoft', 'Toshiba', 'Huawei', 'Xiaomi', 'Vero', 'Razer',
       'Mediacom', 'Samsung', 'Google', 'Fujitsu', 'LG'], dtype=object)

In [5]:
companies={'Apple':0,'HP':1,'Acer':2, 'Asus' : 3, 'Dell' : 4, 'Lenovo': 5, 'Chuwi' : 6, 'MSI':7, 'Microsoft':8,
          'Toshiba':9, 'Huawei'  : 10 , 'Xiaomi' : 11, 'Vero' : 12, 'Razer' : 13,'Mediacom' : 14, 'Samsung' : 15, 
           'Google' : 16, 'Fujitsu' : 17, 'LG' : 18}

data['Company'] = data['Company'].replace(companies)

In [6]:
data['TypeName'].unique()

array(['Ultrabook', 'Notebook', 'Netbook', 'Gaming', '2 in 1 Convertible',
       'Workstation'], dtype=object)

In [7]:
types={ 'Ultrabook' : 1, 'Notebook' : 2, 'Netbook' : 3, 'Gaming' : 4, '2 in 1 Convertible' : 5,'Workstation' : 5}
data['TypeName'] = data['TypeName'].replace(types)

In [8]:
data['ScreenResolution'].unique()

array(['IPS Panel Retina Display 2560x1600', '1440x900',
       'Full HD 1920x1080', 'IPS Panel Retina Display 2880x1800',
       '1366x768', 'IPS Panel Full HD 1920x1080',
       'IPS Panel Retina Display 2304x1440',
       'IPS Panel Full HD / Touchscreen 1920x1080',
       'Full HD / Touchscreen 1920x1080',
       'Touchscreen / Quad HD+ 3200x1800',
       'IPS Panel Touchscreen 1920x1200', 'Touchscreen 2256x1504',
       'Quad HD+ / Touchscreen 3200x1800', 'IPS Panel 1366x768',
       'IPS Panel 4K Ultra HD / Touchscreen 3840x2160',
       'IPS Panel Full HD 2160x1440',
       '4K Ultra HD / Touchscreen 3840x2160', 'Touchscreen 2560x1440',
       '1600x900', 'IPS Panel 4K Ultra HD 3840x2160',
       '4K Ultra HD 3840x2160', 'Touchscreen 1366x768',
       'IPS Panel Full HD 1366x768', 'IPS Panel 2560x1440',
       'IPS Panel Full HD 2560x1440',
       'IPS Panel Retina Display 2736x1824', 'Touchscreen 2400x1600',
       '2560x1440', 'IPS Panel Quad HD+ 2560x1440',
       'IPS Panel 

In [9]:
displays={'IPS Panel Retina Display 2560x1600' : 1, 
          '1440x900' :0 ,
           'Full HD 1920x1080' : 2, 
          'IPS Panel Retina Display 2880x1800' : 3,
           '1366x768' : 0, 
          'IPS Panel Full HD 1920x1080' : 1,
           'IPS Panel Retina Display 2304x1440' : 1,
           'IPS Panel Full HD / Touchscreen 1920x1080' : 2,
           'Full HD / Touchscreen 1920x1080' : 2,
           'Touchscreen / Quad HD+ 3200x1800' : 4,
           'IPS Panel Touchscreen 1920x1200' : 2, 
          'Touchscreen 2256x1504' : 2,
           'Quad HD+ / Touchscreen 3200x1800' : 4 , 
          'IPS Panel 1366x768' : 1,
           'IPS Panel 4K Ultra HD / Touchscreen 3840x2160' : 4,
           'IPS Panel Full HD 2160x1440' : 1,
           '4K Ultra HD / Touchscreen 3840x2160' : 4, 
          'Touchscreen 2560x1440' : 2,
           '1600x900' : 1, 
          'IPS Panel 4K Ultra HD 3840x2160' : 3,
           '4K Ultra HD 3840x2160' : 3, 
          'Touchscreen 1366x768' : 2,
           'IPS Panel Full HD 1366x768' : 1, 
          'IPS Panel 2560x1440' : 1,
           'IPS Panel Full HD 2560x1440' : 1,
           'IPS Panel Retina Display 2736x1824' : 3, 
           'Touchscreen 2400x1600' : 2,
           '2560x1440' : 1, 
           'IPS Panel Quad HD+ 2560x1440' : 3,
           'IPS Panel Quad HD+ 3200x1800' : 3,
           'IPS Panel Quad HD+ / Touchscreen 3200x1800' : 4,
           'IPS Panel Touchscreen 1366x768' : 2, 
          '1920x1080' : 0,
           'IPS Panel Full HD 1920x1200' : 1,
           'IPS Panel Touchscreen / 4K Ultra HD 3840x2160' : 4,
           'IPS Panel Touchscreen 2560x1440' : 2,
           'Touchscreen / Full HD 1920x1080' : 2, 
          'Quad HD+ 3200x1800' : 3,
           'Touchscreen / 4K Ultra HD 3840x2160' : 4,
           'IPS Panel Touchscreen 2400x1600' : 2
         }

disps={
    0:'HD display',
    1:'full HD display',
    2:'full HD  + touch screen display',
    3:'4k display',
    4:'4k + touch screen display'
}

data['ScreenResolution'] = data['ScreenResolution'].replace(displays)

In [10]:
data['Inches'].unique()

array([13.3, 15.6, 15.4, 14. , 12. , 11.6, 17.3, 10.1, 13.5, 12.5, 13. ,
       18.4, 13.9, 12.3, 17. , 15. , 14.1, 11.3])

In [11]:
display_sizes = {13.3 : 13, 15.6 : 16, 15.4 : 16, 14. : 15, 12. : 13, 11.6 : 13, 17.3 : 17, 10.1 : 13, 13.5 : 13,
                 12.5: 13, 13.: 13, 18.4 : 17, 13.9 : 14, 12.3 : 13, 17. : 17 , 15. : 15, 14.1 : 14, 11.3 : 13 
}

data['Inches'] = data['Inches'].replace(display_sizes)
data['Inches'].unique()
#displays = <13, 13 -15, 15 - 16, 16+

array([13., 16., 15., 17., 14.])

In [12]:
data['Cpu'].unique()

array(['Intel Core i5 2.3GHz', 'Intel Core i5 1.8GHz',
       'Intel Core i5 7200U 2.5GHz', 'Intel Core i7 2.7GHz',
       'Intel Core i5 3.1GHz', 'AMD A9-Series 9420 3GHz',
       'Intel Core i7 2.2GHz', 'Intel Core i7 8550U 1.8GHz',
       'Intel Core i5 8250U 1.6GHz', 'Intel Core i3 6006U 2GHz',
       'Intel Core i7 2.8GHz', 'Intel Core M m3 1.2GHz',
       'Intel Core i7 7500U 2.7GHz', 'Intel Core i7 2.9GHz',
       'Intel Core i3 7100U 2.4GHz', 'Intel Atom x5-Z8350 1.44GHz',
       'Intel Core i5 7300HQ 2.5GHz', 'AMD E-Series E2-9000e 1.5GHz',
       'Intel Core i5 1.6GHz', 'Intel Core i7 8650U 1.9GHz',
       'Intel Atom x5-Z8300 1.44GHz', 'AMD E-Series E2-6110 1.5GHz',
       'AMD A6-Series 9220 2.5GHz',
       'Intel Celeron Dual Core N3350 1.1GHz',
       'Intel Core i3 7130U 2.7GHz', 'Intel Core i7 7700HQ 2.8GHz',
       'Intel Core i5 2.0GHz', 'AMD Ryzen 1700 3GHz',
       'Intel Pentium Quad Core N4200 1.1GHz',
       'Intel Atom x5-Z8550 1.44GHz',
       'Intel Celeron Du

In [13]:
pros = ['Intel Core i5 2.3GHz', 'Intel Core i5 1.8GHz',
       'Intel Core i5 7200U 2.5GHz', 'Intel Core i7 2.7GHz',
       'Intel Core i5 3.1GHz', 'AMD A9-Series 9420 3GHz',
       'Intel Core i7 2.2GHz', 'Intel Core i7 8550U 1.8GHz',
       'Intel Core i5 8250U 1.6GHz', 'Intel Core i3 6006U 2GHz',
       'Intel Core i7 2.8GHz', 'Intel Core M m3 1.2GHz',
       'Intel Core i7 7500U 2.7GHz', 'Intel Core i7 2.9GHz',
       'Intel Core i3 7100U 2.4GHz', 'Intel Atom x5-Z8350 1.44GHz',
       'Intel Core i5 7300HQ 2.5GHz', 'AMD E-Series E2-9000e 1.5GHz',
       'Intel Core i5 1.6GHz', 'Intel Core i7 8650U 1.9GHz',
       'Intel Atom x5-Z8300 1.44GHz', 'AMD E-Series E2-6110 1.5GHz',
       'AMD A6-Series 9220 2.5GHz',
       'Intel Celeron Dual Core N3350 1.1GHz',
       'Intel Core i3 7130U 2.7GHz', 'Intel Core i7 7700HQ 2.8GHz',
       'Intel Core i5 2.0GHz', 'AMD Ryzen 1700 3GHz',
       'Intel Pentium Quad Core N4200 1.1GHz',
       'Intel Atom x5-Z8550 1.44GHz',
       'Intel Celeron Dual Core N3060 1.6GHz', 'Intel Core i5 1.3GHz',
       'AMD FX 9830P 3GHz', 'Intel Core i7 7560U 2.4GHz',
       'AMD E-Series 6110 1.5GHz', 'Intel Core i5 6200U 2.3GHz',
       'Intel Core M 6Y75 1.2GHz', 'Intel Core i5 7500U 2.7GHz',
       'Intel Core i3 6006U 2.2GHz', 'AMD A6-Series 9220 2.9GHz',
       'Intel Core i7 6920HQ 2.9GHz', 'Intel Core i5 7Y54 1.2GHz',
       'Intel Core i7 7820HK 2.9GHz', 'Intel Xeon E3-1505M V6 3GHz',
       'Intel Core i7 6500U 2.5GHz', 'AMD E-Series 9000e 1.5GHz',
       'AMD A10-Series A10-9620P 2.5GHz', 'AMD A6-Series A6-9220 2.5GHz',
       'Intel Core i5 2.9GHz', 'Intel Core i7 6600U 2.6GHz',
       'Intel Core i3 6006U 2.0GHz',
       'Intel Celeron Dual Core 3205U 1.5GHz',
       'Intel Core i7 7820HQ 2.9GHz', 'AMD A10-Series 9600P 2.4GHz',
       'Intel Core i7 7600U 2.8GHz', 'AMD A8-Series 7410 2.2GHz',
       'Intel Celeron Dual Core 3855U 1.6GHz',
       'Intel Pentium Quad Core N3710 1.6GHz',
       'AMD A12-Series 9720P 2.7GHz', 'Intel Core i5 7300U 2.6GHz',
       'AMD A12-Series 9720P 3.6GHz',
       'Intel Celeron Quad Core N3450 1.1GHz',
       'Intel Celeron Dual Core N3060 1.60GHz',
       'Intel Core i5 6440HQ 2.6GHz', 'Intel Core i7 6820HQ 2.7GHz',
       'AMD Ryzen 1600 3.2GHz', 'Intel Core i7 7Y75 1.3GHz',
       'Intel Core i5 7440HQ 2.8GHz', 'Intel Core i7 7660U 2.5GHz',
       'Intel Core i7 7700HQ 2.7GHz', 'Intel Core M m3-7Y30 2.2GHz',
       'Intel Core i5 7Y57 1.2GHz', 'Intel Core i7 6700HQ 2.6GHz',
       'Intel Core i3 6100U 2.3GHz', 'AMD A10-Series 9620P 2.5GHz',
       'AMD E-Series 7110 1.8GHz', 'Intel Celeron Dual Core N3350 2.0GHz',
       'AMD A9-Series A9-9420 3GHz', 'Intel Core i7 6820HK 2.7GHz',
       'Intel Core M 7Y30 1.0GHz', 'Intel Xeon E3-1535M v6 3.1GHz',
       'Intel Celeron Quad Core N3160 1.6GHz',
       'Intel Core i5 6300U 2.4GHz', 'Intel Core i3 6100U 2.1GHz',
       'AMD E-Series E2-9000 2.2GHz',
       'Intel Celeron Dual Core N3050 1.6GHz',
       'Intel Core M M3-6Y30 0.9GHz', 'AMD A9-Series 9420 2.9GHz',
       'Intel Core i5 6300HQ 2.3GHz', 'AMD A6-Series 7310 2GHz',
       'Intel Atom Z8350 1.92GHz', 'Intel Xeon E3-1535M v5 2.9GHz',
       'Intel Core i5 6260U 1.8GHz',
       'Intel Pentium Dual Core N4200 1.1GHz',
       'Intel Celeron Quad Core N3710 1.6GHz', 'Intel Core M 1.2GHz',
       'AMD A12-Series 9700P 2.5GHz', 'Intel Core i7 7500U 2.5GHz',
       'Intel Pentium Dual Core 4405U 2.1GHz',
       'AMD A4-Series 7210 2.2GHz', 'Intel Core i7 6560U 2.2GHz',
       'Intel Core M m7-6Y75 1.2GHz', 'AMD FX 8800P 2.1GHz',
       'Intel Core M M7-6Y75 1.2GHz', 'Intel Core i5 7200U 2.50GHz',
       'Intel Core i5 7200U 2.70GHz', 'Intel Atom X5-Z8350 1.44GHz',
       'Intel Core i5 7200U 2.7GHz', 'Intel Core M 1.1GHz',
       'Intel Pentium Dual Core 4405Y 1.5GHz',
       'Intel Pentium Quad Core N3700 1.6GHz', 'Intel Core M 6Y54 1.1GHz',
       'Intel Core i7 6500U 2.50GHz',
       'Intel Celeron Dual Core N3350 2GHz',
       'Samsung Cortex A72&A53 2.0GHz', 'AMD E-Series 9000 2.2GHz',
       'Intel Core M 6Y30 0.9GHz', 'AMD A9-Series 9410 2.9GHz']

prcsr = {}
for i in pros:
    if "Celeron" in i:
        prcsr[i] = 0
    elif "Pentium" in i:
        prcsr[i] = 0
    elif "Core M" in i:
        prcsr[i] = 0
    elif "Atom" in i:
        prcsr[i] = 0
    elif "i3" in i:
        prcsr[i] = 1
    elif "i5" in i:
        prcsr[i] = 2
    elif "i7" in i:
        prcsr[i] = 3
    elif "Xeon" in i:
        prcsr[i] = 4
    elif "AMD E-Series" in i:
        prcsr[i] = 5
    elif "AMD A4-Series" in i:
        prcsr[i] = 6
    elif "AMD Ryzen" in i:
        prcsr[i] = 7
    elif "AMD A6-Series" in i:
        prcsr[i] = 8
    elif "AMD A6-Series" in i:
        prcsr[i] = 9
    elif "AMD A9-Series" in i:
        prcsr[i] = 10
    elif "AMD A10-Series" in i:
        prcsr[i] = 11
    elif "AMD A11-Series" in i:
        prcsr[i] = 12
    elif "AMD A12-Series" in i:
        prcsr[i] = 13
    elif "AMD FX" in i:
        prcsr[i] = 14
    elif "Samsung" in i:
        prcsr[i] = 15
    elif "AMD R4" in i:
        prcsr[i] = 16
    else:
        prcsr[i] = 17
        
print(prcsr)

{'Intel Core i5 2.3GHz': 2, 'Intel Core i5 1.8GHz': 2, 'Intel Core i5 7200U 2.5GHz': 2, 'Intel Core i7 2.7GHz': 3, 'Intel Core i5 3.1GHz': 2, 'AMD A9-Series 9420 3GHz': 10, 'Intel Core i7 2.2GHz': 3, 'Intel Core i7 8550U 1.8GHz': 3, 'Intel Core i5 8250U 1.6GHz': 2, 'Intel Core i3 6006U 2GHz': 1, 'Intel Core i7 2.8GHz': 3, 'Intel Core M m3 1.2GHz': 0, 'Intel Core i7 7500U 2.7GHz': 3, 'Intel Core i7 2.9GHz': 3, 'Intel Core i3 7100U 2.4GHz': 1, 'Intel Atom x5-Z8350 1.44GHz': 0, 'Intel Core i5 7300HQ 2.5GHz': 2, 'AMD E-Series E2-9000e 1.5GHz': 5, 'Intel Core i5 1.6GHz': 2, 'Intel Core i7 8650U 1.9GHz': 3, 'Intel Atom x5-Z8300 1.44GHz': 0, 'AMD E-Series E2-6110 1.5GHz': 5, 'AMD A6-Series 9220 2.5GHz': 8, 'Intel Celeron Dual Core N3350 1.1GHz': 0, 'Intel Core i3 7130U 2.7GHz': 1, 'Intel Core i7 7700HQ 2.8GHz': 3, 'Intel Core i5 2.0GHz': 2, 'AMD Ryzen 1700 3GHz': 7, 'Intel Pentium Quad Core N4200 1.1GHz': 0, 'Intel Atom x5-Z8550 1.44GHz': 0, 'Intel Celeron Dual Core N3060 1.6GHz': 0, 'Intel C

In [14]:
data['Cpu'] = data['Cpu'].replace(prcsr)

In [15]:
print(data['Ram'].unique())
print(data['Memory'].unique())

['8GB' '16GB' '4GB' '2GB' '12GB' '6GB' '32GB' '24GB' '64GB']
['128GB SSD' '128GB Flash Storage' '256GB SSD' '512GB SSD' '500GB HDD'
 '256GB Flash Storage' '1TB HDD' '32GB Flash Storage'
 '128GB SSD +  1TB HDD' '256GB SSD +  256GB SSD' '64GB Flash Storage'
 '256GB SSD +  1TB HDD' '256GB SSD +  2TB HDD' '32GB SSD' '2TB HDD'
 '64GB SSD' '1.0TB Hybrid' '512GB SSD +  1TB HDD' '1TB SSD'
 '256GB SSD +  500GB HDD' '128GB SSD +  2TB HDD' '512GB SSD +  512GB SSD'
 '16GB SSD' '16GB Flash Storage' '512GB SSD +  256GB SSD'
 '512GB SSD +  2TB HDD' '64GB Flash Storage +  1TB HDD' '180GB SSD'
 '1TB HDD +  1TB HDD' '32GB HDD' '1TB SSD +  1TB HDD'
 '512GB Flash Storage' '128GB HDD' '240GB SSD' '8GB SSD' '508GB Hybrid'
 '1.0TB HDD' '512GB SSD +  1.0TB Hybrid' '256GB SSD +  1.0TB Hybrid']


In [16]:
import re
def ram_convert(s):
    l=re.findall(r'\d+',s)
    return float(l[0])
data["Ram"] = data["Ram"].apply(ram_convert)

In [17]:
memory = {
    '128GB SSD' : 1, '128GB Flash Storage' : 1, '256GB SSD' :2, '512GB SSD':3, '500GB HDD':3,
 '256GB Flash Storage' :2, '1TB HDD':3, '32GB Flash Storage' : 0,
 '128GB SSD +  1TB HDD' :4, '256GB SSD +  256GB SSD' :2, '64GB Flash Storage' :0, 
 '256GB SSD +  1TB HDD': 4,  '256GB SSD +  2TB HDD' : 5, '32GB SSD' :0, '2TB HDD' :5 ,
 '64GB SSD' : 0,'1.0TB Hybrid' : 6,'512GB SSD +  1TB HDD':4, '1TB SSD' : 4,
 '256GB SSD +  500GB HDD' : 3,'128GB SSD +  2TB HDD' : 5,'512GB SSD +  512GB SSD' : 3,
 '16GB SSD' : 0,'16GB Flash Storage' : 0,'512GB SSD +  256GB SSD' : 3,
 '512GB SSD +  2TB HDD' : 5,'64GB Flash Storage +  1TB HDD' : 4,'180GB SSD' : 0,
 '1TB HDD +  1TB HDD' : 4, '32GB HDD' : 0, '1TB SSD +  1TB HDD' : 4,
 '512GB Flash Storage' : 2, '128GB HDD' : 1,'240GB SSD' : 1,'8GB SSD' : 0,'508GB Hybrid' : 6,
 '1.0TB HDD' : 4, '512GB SSD +  1.0TB Hybrid' : 6, '256GB SSD +  1.0TB Hybrid' : 6,
}

#storage : <128gb-0, 128-1, 256-2, 512-3, 1tb=4, 2TB-5, 1tb_hybrid-6

data['Memory'] = data['Memory'].replace(memory)

In [18]:
data['Memory'].unique()

array([1, 2, 3, 0, 4, 5, 6], dtype=int64)

In [19]:
data['Gpu'].unique()

array(['Intel Iris Plus Graphics 640', 'Intel HD Graphics 6000',
       'Intel HD Graphics 620', 'AMD Radeon Pro 455',
       'Intel Iris Plus Graphics 650', 'AMD Radeon R5',
       'Intel Iris Pro Graphics', 'Nvidia GeForce MX150',
       'Intel UHD Graphics 620', 'Intel HD Graphics 520',
       'AMD Radeon Pro 555', 'AMD Radeon R5 M430',
       'Intel HD Graphics 615', 'AMD Radeon Pro 560',
       'Nvidia GeForce 940MX', 'Intel HD Graphics 400',
       'Nvidia GeForce GTX 1050', 'AMD Radeon R2', 'AMD Radeon 530',
       'Nvidia GeForce 930MX', 'Intel HD Graphics',
       'Intel HD Graphics 500', 'Nvidia GeForce 930MX ',
       'Nvidia GeForce GTX 1060', 'Nvidia GeForce 150MX',
       'Intel Iris Graphics 540', 'AMD Radeon RX 580',
       'Nvidia GeForce 920MX', 'AMD Radeon R4 Graphics', 'AMD Radeon 520',
       'Nvidia GeForce GTX 1070', 'Nvidia GeForce GTX 1050 Ti',
       'Nvidia GeForce MX130', 'AMD R4 Graphics',
       'Nvidia GeForce GTX 940MX', 'AMD Radeon RX 560',
       'Nvid

In [20]:
gpu= ['Intel Iris Plus Graphics 640', 'Intel HD Graphics 6000',
       'Intel HD Graphics 620', 'AMD Radeon Pro 455',
       'Intel Iris Plus Graphics 650', 'AMD Radeon R5',
       'Intel Iris Pro Graphics', 'Nvidia GeForce MX150',
       'Intel UHD Graphics 620', 'Intel HD Graphics 520',
       'AMD Radeon Pro 555', 'AMD Radeon R5 M430',
       'Intel HD Graphics 615', 'AMD Radeon Pro 560',
       'Nvidia GeForce 940MX', 'Intel HD Graphics 400',
       'Nvidia GeForce GTX 1050', 'AMD Radeon R2', 'AMD Radeon 530',
       'Nvidia GeForce 930MX', 'Intel HD Graphics',
       'Intel HD Graphics 500', 'Nvidia GeForce 930MX ',
       'Nvidia GeForce GTX 1060', 'Nvidia GeForce 150MX',
       'Intel Iris Graphics 540', 'AMD Radeon RX 580',
       'Nvidia GeForce 920MX', 'AMD Radeon R4 Graphics', 'AMD Radeon 520',
       'Nvidia GeForce GTX 1070', 'Nvidia GeForce GTX 1050 Ti',
       'Nvidia GeForce MX130', 'AMD R4 Graphics',
       'Nvidia GeForce GTX 940MX', 'AMD Radeon RX 560',
       'Nvidia GeForce 920M', 'AMD Radeon R7 M445', 'AMD Radeon RX 550',
       'Nvidia GeForce GTX 1050M', 'Intel HD Graphics 515',
       'AMD Radeon R5 M420', 'Intel HD Graphics 505',
       'Nvidia GTX 980 SLI', 'AMD R17M-M1-70', 'Nvidia GeForce GTX 1080',
       'Nvidia Quadro M1200', 'Nvidia GeForce 920MX ',
       'Nvidia GeForce GTX 950M', 'AMD FirePro W4190M ',
       'Nvidia GeForce GTX 980M', 'Intel Iris Graphics 550',
       'Nvidia GeForce 930M', 'Intel HD Graphics 630',
       'AMD Radeon R5 430', 'Nvidia GeForce GTX 940M',
       'Intel HD Graphics 510', 'Intel HD Graphics 405',
       'AMD Radeon RX 540', 'Nvidia GeForce GT 940MX',
       'AMD FirePro W5130M', 'Nvidia Quadro M2200M', 'AMD Radeon R4',
       'Nvidia Quadro M620', 'AMD Radeon R7 M460',
       'Intel HD Graphics 530', 'Nvidia GeForce GTX 965M',
       'Nvidia GeForce GTX1080', 'Nvidia GeForce GTX1050 Ti',
       'Nvidia GeForce GTX 960M', 'AMD Radeon R2 Graphics',
       'Nvidia Quadro M620M', 'Nvidia GeForce GTX 970M',
       'Nvidia GeForce GTX 960<U+039C>', 'Intel Graphics 620',
       'Nvidia GeForce GTX 960', 'AMD Radeon R5 520',
       'AMD Radeon R7 M440', 'AMD Radeon R7', 'Nvidia Quadro M520M',
       'Nvidia Quadro M2200', 'Nvidia Quadro M2000M',
       'Intel HD Graphics 540', 'Nvidia Quadro M1000M', 'AMD Radeon 540',
       'Nvidia GeForce GTX 1070M', 'Nvidia GeForce GTX1060',
       'Intel HD Graphics 5300', 'AMD Radeon R5 M420X',
       'AMD Radeon R7 Graphics', 'Nvidia GeForce 920',
       'Nvidia GeForce 940M', 'Nvidia GeForce GTX 930MX',
       'AMD Radeon R7 M465', 'AMD Radeon R3', 'Nvidia GeForce GTX 1050Ti',
       'AMD Radeon R7 M365X', 'AMD Radeon R9 M385',
       'Intel HD Graphics 620 ', 'Nvidia Quadro 3000M',
       'Nvidia GeForce GTX 980 ', 'AMD Radeon R5 M330',
       'AMD FirePro W4190M', 'AMD FirePro W6150M', 'AMD Radeon R5 M315',
       'Nvidia Quadro M500M', 'AMD Radeon R7 M360',
       'Nvidia Quadro M3000M', 'Nvidia GeForce 960M', 'ARM Mali T860 MP4']

gpus={}

for i in gpu:
    if "ARM Mali" in i:
        gpus[i] = 0
        
    elif "AMD Radeon" in i:
        gpus[i] = 1
        
    elif "AMD FirePro" in i:
        gpus[i] = 2
        
    elif "AMD Radeon Pro" in i:
        gpus[i] = 3
        
    elif "Intel HD Graphics" or "Intel Graphics" in i:
        gpus[i] = 4
    
    elif "Intel Iris Plus" in i:
        gpus[i] = 5
    
    elif "Intel Iris Pro" in i:
        gpus[i] = 6
    
    elif "Intel UHD Graphics" in i:
        gpus[i] = 7
    
    elif "Nvidia GeForce" in i:
        gpus[i] = 8
    
    elif "Nvidia Quadro" in i:
        gpus[i] = 9
    
    elif "Nvidia GTX" in i:
        gpus[i] = 10
    else:
        gpus['others'] = 11

        
data['Gpu'] = data['Gpu'].replace(gpus)

In [21]:
data['OpSys'].unique()

array(['macOS', 'No OS', 'Windows 10', 'Mac OS X', 'Linux', 'Android',
       'Windows 10 S', 'Chrome OS', 'Windows 7'], dtype=object)

In [22]:
os= {'macOS' :0, 'No OS':1, 'Windows 10':2, 'Mac OS X':0, 'Linux':4, 'Android':5, 'Windows 10 S':2, 
     'Chrome OS':6, 'Windows 7':7}

data['OpSys'] = data['OpSys'].replace(os)

In [23]:
data.head()

Company  TypeName  Inches  ScreenResolution  Cpu   Ram  Memory  Gpu  OpSys  \
0        0         1    13.0                 1    2   8.0       1    4      0   
1        0         1    13.0                 0    2   8.0       1    4      0   
2        1         2    16.0                 2    2   8.0       2    4      1   
3        0         1    16.0                 3    3  16.0       3    1      0   
4        0         1    13.0                 1    2   8.0       2    4      0   

   Weight  
0  1.37kg  
1  1.34kg  
2  1.86kg  
3  1.83kg  
4  1.37kg

In [24]:
data['Weight'].unique()

array(['1.37kg', '1.34kg', '1.86kg', '1.83kg', '2.1kg', '2.04kg', '1.3kg',
       '1.6kg', '2.2kg', '0.92kg', '1.22kg', '0.98kg', '2.5kg', '1.62kg',
       '1.91kg', '2.3kg', '1.35kg', '1.88kg', '1.89kg', '1.65kg',
       '2.71kg', '1.2kg', '1.44kg', '2.8kg', '2kg', '2.65kg', '2.77kg',
       '3.2kg', '0.69kg', '1.49kg', '2.4kg', '2.13kg', '2.43kg', '1.7kg',
       '1.4kg', '1.8kg', '1.9kg', '3kg', '1.252kg', '2.7kg', '2.02kg',
       '1.63kg', '1.96kg', '1.21kg', '2.45kg', '1.25kg', '1.5kg',
       '2.62kg', '1.38kg', '1.58kg', '1.85kg', '1.23kg', '1.26kg',
       '2.16kg', '2.36kg', '2.05kg', '1.32kg', '1.75kg', '0.97kg',
       '2.9kg', '2.56kg', '1.48kg', '1.74kg', '1.1kg', '1.56kg', '2.03kg',
       '1.05kg', '4.4kg', '1.90kg', '1.29kg', '2.0kg', '1.95kg', '2.06kg',
       '1.12kg', '1.42kg', '3.49kg', '3.35kg', '2.23kg', '4.42kg',
       '2.69kg', '2.37kg', '4.7kg', '3.6kg', '2.08kg', '4.3kg', '1.68kg',
       '1.41kg', '4.14kg', '2.18kg', '2.24kg', '2.67kg', '2.14kg',
       '1.

In [25]:
def weight(w):
    if w<1.20:
        return 1
    elif w<2:
        return 2
    elif w<3:
        return 3
    elif w<4:
        return 4
    else:
        return 5
    
def convert_weight(x):
    if "kg" in x:
        return weight(float(x.replace("kg","").strip()))
    elif "g" in weight:
        return x(float(x.replace("g","").strip())/1000)
    elif "k" in x:
        return weight(float(x.replace("k","").strip()))



data['Weight'] = data['Weight'].apply(convert_weight)

In [26]:
data['Weight'].unique()

array([2, 3, 1, 4, 5], dtype=int64)

In [27]:
print(data_set['Price'].max())
data.head()

324954.72


Company  TypeName  Inches  ScreenResolution  Cpu   Ram  Memory  Gpu  OpSys  \
0        0         1    13.0                 1    2   8.0       1    4      0   
1        0         1    13.0                 0    2   8.0       1    4      0   
2        1         2    16.0                 2    2   8.0       2    4      1   
3        0         1    16.0                 3    3  16.0       3    1      0   
4        0         1    13.0                 1    2   8.0       2    4      0   

   Weight  
0       2  
1       2  
2       2  
3       2  
4       2

In [31]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

bins = [0, 100000, 200000, 300000, np.inf]
labels = [0, 1, 2, 3]
data['Price_cat'] = pd.cut(data_set['Price'], bins=bins, labels=labels)

dt = DecisionTreeClassifier()
x = data.drop(["Price_cat"], axis=1)
y = data["Price_cat"]
X_train, X_test, Y_train, Y_test = train_test_split(x, y)
dt.fit(X_train, Y_train)
Y_pred = dt.predict(X_test)
accuracy = accuracy_score(Y_test, Y_pred)

print("Accuracy:", accuracy)


Accuracy: 0.9049079754601227
